---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: FORESTRY-README.md
  label: Bienvenue - Premiers pas
  read_only: true
- type: heading
  label: L'association
- type: document
  path: asso/presentation.md
  label: Présentation
- type: document
  path: asso/benevoles.md
  label: Les bénévoles
- type: document
  path: asso/nous-aider.md
  label: Comment nous aider ?
- type: heading
  label: Adopter un chat
- type: document
  path: adopter/comment.md
  label: Pourquoi et comment ?
- type: document
  path: adopter/annonces.md
  label: Chats à l'adoption
- type: document
  path: adopter/nouvelles.md
  label: Des nouvelles ...
- type: heading
  label: Actualités
- type: directory
  path: blog/urgences
  label: Urgences
  create: documents
  match: "**/*"
  exclude: "*README.md"
  new_doc_ext: md
- type: directory
  path: blog/histoires
  label: Les histoires
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: jekyll-posts
  label: Blog
  create: all
- type: document
  path: contact.md
  label: Contact
- type: document
  path: _config.yml
  label: Config
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.84.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public --environment staging
version: 0.42.1
